Handle `StorageException`s when loading blobs.
androidx/gcp-gradle-build-cache pull request #22
Opened 2022-05-12 18:17 UTC by tikurahul

* Fetching blobs and `ReadChannel`s can fail. Treat them as cache misses.

2022-05-12 21:11 UTC, liutikas requested changes
Please update README.md as well.

2022-05-12 21:55 UTC, tikurahul commented
Done.

2022-05-13 00:20 UTC, liutikas reviewed
Please update line 11 of README.md as well.

2022-05-13 14:53 UTC, tikurahul commented
Sorry, missed that. Now fixed.

2022-05-13 23:36 UTC, liutikas approved these changes

2022-05-13 23:36 UTC, merged